### ISSUE TITLE
Alertify bug

### ISSUE THREAD

**Issue by vikram-wri231** [webreinvent/vaahcms#1]
When we click on any alertify option, the screen is disable to do any activity then we have to reload the page.

so, we have to remove the link of alertify.css at  **...\vendor\vaahcms\admin\default\assets.json**
and remove  **"vendor/vaahcms/admin/default/lib/alertify/css/themes/alertify.css"**.

**Comment by modernpk** [comment]
@vikram-wri231 
This issue is fixed, just run `composer update` and make sure you have vaahcms `0.3.1`
