### ISSUE TITLE
Add Table Property to the method

### ISSUE THREAD

**Issue by themodernpk** [webreinvent/vaahcms#142]
@we-vikram-wri231 

The following method should accept `table` 

https://github.com/webreinvent/vaahcms/blob/446587e21857453757490938a8ca024f1c4e0350/Libraries/VaahSeeder.php#L61

**Comment by themodernpk** [comment]
true for other methods as well

**Comment by we-anil-y001** [comment]
@themodernpk sir this was already done in both vaahcms 
vaahcms1x - https://github.com/webreinvent/vaahcms/blob/1.x/Libraries/VaahSeeder.php#L61
vaahcms2x - https://github.com/webreinvent/vaahcms/blob/2.x/Libraries/VaahSeeder.php#L63
