### ISSUE TITLE
Missing FormGroup (?)

### ISSUE THREAD

**Issue by playazkah** [webreinvent/vaahcms#186]
I'm trying to install VaahCMS 2.x, it's a fresh install.

> NPM Version: 10.1.0
> Node Version: v20.7.0
> PHP Version: v8.2.10
> Laravel Version: v10.19.0

I'm following these steps from the documentation page:

[https://docs.vaah.dev/vaahcms-2/getting-started/installation
](https://docs.vaah.dev/vaahcms-2/getting-started/installation
)

Everything works fine until I'm trying to install the **BulmaBlogTheme** on the Dependencies setup page.

I get an error while installing the theme: **Class "VaahCms\Modules\Cms\Models\FormGroup" not found**

![img_2023-09-20_163848732](https://github.com/webreinvent/vaahcms/assets/43482286/18403e05-618f-43c6-ac9b-a3181d9f5952)

**Comment by themodernpk** [comment]
@playazkah you click on `Skip` button for the time being. We're working on it to fix it, it's a known bug.

**Comment by themodernpk** [comment]
@playazkah this issue has been fixed
