### ISSUE TITLE
Slack URL not active anymore

### ISSUE THREAD

**Issue by crydotsnake** [webreinvent/vaahcms#40]
Hello!, i just would like too let you know, that the Slack url is not active anymore.
![Bildschirmfoto 2021-10-02 um 09 19 16](https://user-images.githubusercontent.com/39345336/135707492-b2b34cef-98cf-40d1-bd75-330a8b3adcf8.png)

Englisch
The link is no longer active

To join this workspace, you must ask the person who originally invited you to send you a new link.

https://vaah.slack.com/join/shared_invite/zt-tlop66za-yKKtiuMZ5S4lAYUQ6gtfMw#/shared-invite-legacy/error

**Comment by themodernpk** [comment]
Hi @crydotsnake, the updated invitation link is following:

https://join.slack.com/t/vaah/shared_invite/zt-wgvx75rr-tuAhGtjRweCR~DEVSTFcSQ 

It is also updated on the website.
