### ISSUE TITLE
Does not work with Laravel 9 - Using Laravel Valet

### ISSUE THREAD

**Issue by prodkt** [webreinvent/vaahcms#67]
1. Create local DB (e.g. prodkt-cms)
2. Install Laravel via Composer
3. Manual adjustment to env file to successful connection to local mysql db
4. Confirm success using Valet (e.g. prodkt-cms.test) --- CONFIRMED
5. run npx vaah cms:install
6.  Creating Project Folder
  ✔ Creating Project Folder
  ✔ Downloading VaahCMS
  ✔ Extracting VaahCMS Files
  ✔ Installing Dependencies via Composer (Takes 3 - 5 minutes)
  ✔ Installing VaahCMS...
        VaahCMS Installed!
7. Visit (e.g. prodkt-cms.test/vaahcms/setup --- 404 NOT FOUND
8. run php artisan serve
9. visit http://127.0.0.1:8000/vaahcms/setup --- 404 NOT FOUND
10. Stop serve
11. run composer install
12. Visit (e.g. prodkt-cms.test/vaahcms/setup --- 404 NOT FOUND
13. run php artisan serve
14. visit http://127.0.0.1:8000/vaahcms/setup --- 404 NOT FOUND
15. Stop serve
16. Run php artisan vendor:publish --provider='WebReinvent\VaahCms\VaahCmsServiceProvider' --tag=assets --force
        No publishable resources for tag [assets].
        Publishing complete.
17. run php artisan vendor:publish --provider='WebReinvent\VaahCms\VaahCmsServiceProvider' --tag=config --force
        No publishable resources for tag [assets].
        Publishing complete.
18. Visit (e.g. prodkt-cms.test/vaahcms/setup --- 404 NOT FOUND
19. run php artisan serve
20. visit http://127.0.0.1:8000/vaahcms/setup --- 404 NOT FOUND
21. visit http://prodkt-cms.test/backend --- 404 NOT FOUND
22. php artisan serve
23. visit http://127.0.0.1:8000/backend --- 404 NOT FOUND

Is this project not compatible with macOS users utilizing Valet or are we missing something here? 

Thank you!

**Comment by themodernpk** [comment]
@prodkt At the moment it's using Laravel 8, you can give it a try and let us know if you still face any issues. We'll test it with Laravel Valet at our end as well. Though, I think it should have been working.

**Comment by prodkt** [comment]
@themodernpk Thanks for the quick response.

This may be a Laravel/Valet/Vaah issue. Here's what I've just tried that seems to give me the exact same result with Laravel 8...

1. composer create-project laravel/laravel:^8.0 example-app
2. vaah cms:install
✔ Creating Project Folder
✔ Creating Project Folder
✔ Downloading VaahCMS
✔ Extracting VaahCMS Files
✔ Installing Dependencies via Composer (Takes 3 - 5 minutes)
✔ Installing VaahCMS...
VaahCMS Installed!
3. visit http://example-app.test/vaahcms/setup --- 404 NOT FOUND
4. php artisan serve
5. visit http://127.0.0.1:8000/vaahcms/setup --- 404 NOT FOUND

Laravel v8.83.15 (PHP v8.1.6)

Original post: Laravel v9.16.0 (PHP v8.1.6)

Hope this help! Let me know if you'd like any further documentation from me.

**Comment by themodernpk** [comment]
@prodkt 

I wasn't able to replicate the issue, it worked perfectly fine with Laravel Valet on Mac OS, hope the following screenshot helps:

[https://prnt.sc/kELyFqYVgk1t ](https://prnt.sc/kELyFqYVgk1t )

**Comment by prodkt** [comment]
I get something very similar. But what I don't get is an accessible setup with Vaah. You'll notice the 404. From the cli can you see anything can would standout as the issue?

![Screen Shot 2022-06-04 at 1 20 07 AM](https://user-images.githubusercontent.com/101760605/171989218-756ae3da-c1f5-4f85-a7ef-c39498cc9b33.png)
![Screen Shot 2022-06-04 at 1 20 57 AM](https://user-images.githubusercontent.com/101760605/171989221-e769484c-aed7-4a92-865d-affc891cbc5a.png)

**Comment by themodernpk** [comment]
@prodkt please join the slack channel, we can discuss over there.

**Comment by prodkt** [comment]
Absolutely. Can you link me the docs for that lead me here.

![Screen Shot 2022-06-04 at 1 30 42 AM](https://user-images.githubusercontent.com/101760605/171989513-06f74f31-3878-474f-8434-c720aa6518fa.png)

**Comment by themodernpk** [comment]
Here's the link https://join.slack.com/t/vaah/shared_invite/zt-wgvx75rr-tuAhGtjRweCR~DEVSTFcSQ

**Comment by themodernpk** [comment]
@prodkt we'll fix the link. As we collaborated on slack, it seems like you're missing some steps.
