### ISSUE TITLE
Unable to create instance with docker / laravel sail

### ISSUE THREAD

**Issue by MisterMarlu** [webreinvent/vaahcms#69]
Hi, seems like there is a problem when using laravel/sail to start the cms in a docker container. There is a CSRF token mismatch.
![Bildschirmfoto vom 2022-08-04 12-30-43](https://user-images.githubusercontent.com/15226569/182826197-5da54920-5125-4ec8-95fb-cbb4e66f55be.png)

To reproduce it, here are my steps (working on Ubuntu 20.04):

`npx vaah cms:install`
`cd vaahcms`

_Changing db connection in .env file_
```
DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=
DB_DATABASE=test
DB_USERNAME=test
DB_PASSWORD=test
```

`./vendor/bin/sail up`

In the installer I can connect to the database but when I click "Save & Next" the error is thrown (419).

**Comment by themodernpk** [comment]
@MisterMarlu 

You don't need to do any changes in `.env` files. There is a wizard to set up the cms, all you need to do is visit `<domain or localhost>/public/vaahcms/setup`, and cms will automatically generate the required `env` files.

**Comment by MisterMarlu** [comment]
@themodernpk to create an empty db in the mysql container sail need a db name, user and password and using environment variables for this:
![Bildschirmfoto vom 2022-08-04 13-07-13](https://user-images.githubusercontent.com/15226569/182832658-7e33bf63-b05a-42f4-b2ba-d2e8f4f50f0d.png)

But even without editing the `.env` file the error with the CSRF token missmatch will appear.

The steps above without editing the `.env` file there is no db in the mysql container. Anyway, with laravel/sail I cannot install the cms :(

**Comment by themodernpk** [comment]
@MisterMarlu if you can join Slack https://join.slack.com/t/vaah/shared_invite/zt-wgvx75rr-tuAhGtjRweCR~DEVSTFcSQ , I can help you out.

**Comment by themodernpk** [comment]
@MisterMarlu as per our session, we found out that during `setup wizard` it generates a `.env.` file which was causing `419` error. We'll try to fix it in the next version.
