### ISSUE TITLE
Error in creating Media

### ISSUE THREAD

**Issue by jadvillafania** [webreinvent/vaahcms#79]
I have a fresh install and tried to create a Media. The upload is working fine. I can see on the logs that the details of the uploaded image is sent back. However, when I try to complete the form and click the "Save & New" button, I get error messages. Checking the payload of the request, those fields are not being sent to the controller. Please see the attached files as reference.

![image](https://user-images.githubusercontent.com/24929358/192763703-80bf4057-f574-4068-a2de-1f45721feaef.png)

![image](https://user-images.githubusercontent.com/24929358/192764316-534a35b0-37ca-476c-aa3b-37f23ddd46a1.png)

**Comment by themodernpk** [comment]
@jadvillafania Thanks for raising the issue, it will be addressed soon.
